[package]
name = "template-gettext-extractor"
description = "Gettext strings extractor in template files"
keywords = ["gettext", "extractor", "template", "mustache"]
version = "0.1.0"
authors = ["Kevin Traini <kevin@ktraini.com>"]
readme = "README.md"
homepage = "https://github.com/Gashmob/template-gettext-extractor"
repository = "https://github.com/Gashmob/template-gettext-extractor"
license = "GPL-2.0-or-later"
categories = ["command-line-utilities", "development-tools"]
edition = "2024"
exclude = [
    ".github",
    "tools",
    "flake.nix",
    "flake.lock",
    "tge.nix",
    ".envrc",
    ".editorconfig",
]

[[bin]]
name = "tge"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.6", features = ["derive", "wrap_help", "string", "cargo"] }
regex = "1.13.1"
vfs = "0.13.0"

[dev-dependencies]
pretty_assertions = "1.4.1"
